version: "3.8"

networks:
  neo4j:

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: neo4j-examples/movies-php-client:${TAG-latest}
    volumes:
      - .:/opt/project
    env_file:
      - ${ENV_FILE-.env.example}
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - neo4j
    depends_on:
      - db

  db:
    image: neo4j:5
    user: ${UID-1000}:${GID-1000}
    healthcheck:
      test: bash /healthcheck.bash
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ${ENV_FILE-.env.example}
    volumes:
      - ./docker/db/import:/var/lib/neo4j/import
      - ./docker/db/healthcheck.bash:/healthcheck.bash
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j