version: "3.8"

networks:
  neo4j:

services:
  backend:
    image: composer:2.5
    volumes:
      - ./:/opt/project
    working_dir: /opt/project
    command: composer run start
    env_file:
      - ${ENV_FILE-.env.example}
    ports:
      - "8080:8080"
    networks:
      - neo4j

  db:
    image: neo4j:5
    user: ${UID-1000}:${GID-1000}
    healthcheck:
      test: bash /healthcheck.bash
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ${ENV_FILE-.env.example}
    volumes:
      - ./import:/var/lib/neo4j/import
      - ./healthcheck.bash:/healthcheck.bash
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j
