version: "3.8"

networks:
  neo4j:

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: neo4j-examples/movies-php-client:${TAG-latest}
    volumes:
      - .:/opt/project
    env_file:
      - ${ENV_FILE-.env.example}
    ports:
      - "8080:8080"
    networks:
      - neo4j
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
      args:
        NEO4J_VERSION: ${NEO4J_VERSION-5}
    image: neo4j-examples/neo4j-movies:${NEO4J_VERSION-5}
    env_file:
      - ${ENV_FILE-.env.example}
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j