name: PHP

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions

  e2e:
    name: End to end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neo4j-version: [ "4.4", "4.4-enterprise", "5", "5-enterprise" ]

    steps:
      - name: Check out project sources
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: |
          docker compose up -d --build --wait
          docker run -w /e2e -v $PWD/tests/movies-harness:/e2e --network host cypress/included:12.12.0
        env:
          NEO4J_VERSION: ${{ matrix.neo4j-version }}
